[package]
name = "easy-ext"
version = "0.1.5"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/easy-ext"
documentation = "https://docs.rs/easy-ext/"
keywords = ["trait", "macros", "attribute"]
categories = ["rust-patterns"]
readme = "README.md"
description = """
An attribute macro for easily writing extension trait pattern.
"""

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
