[package]
name = "easy-ext"
version = "0.1.6"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/easy-ext"
homepage = "https://github.com/taiki-e/easy-ext"
documentation = "https://docs.rs/easy-ext"
keywords = ["trait", "macros", "attribute"]
categories = ["rust-patterns"]
readme = "README.md"
description = """
An attribute macro for easily writing extension trait pattern.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[dev-dependencies]
rustversion = "1.0"
trybuild = "1.0"
